### ISSUE TITLE
counter example

### ISSUE THREAD

**Issue by shimpe** [maxtuno/Phi#1]
in the file in abstract_binary_search_3000_years_problem_solved.py, set

zero = 18000

then run the code. 

Result: it takes "forever" (I didn't wait "forever" of course) to get an answer.

**Comment by maxtuno** [comment]
That is just an old example, it isn't anything important, look at the official algorithm. (that's just an old thing) https://github.com/maxtuno/Phi/blob/master/ABS_Final.py

**Comment by shimpe** [comment]
Also with final version, problems exist if the sum is not guaranteed to be found:

E.g. find sum of 
75876 in [419, 3064, 3279, 5588, 9279, 10182, 10733, 11121, 11961, 12250, 12429, 14054, 14191, 15990, 16094, 16211]

took 45 seconds to report "No solution" on my pc

and sum of 

19822 in [1166, 2063, 2328, 3396, 4546, 6817, 7417, 7497, 8398, 9816, 11221, 11434, 12068, 12429, 13584, 13743, 14325, 14921]

seems to take a lot longer (it has been running for several minutes now).

**Comment by maxtuno** [comment]
If you look, the solution is a multiset, the algorithm is not intended for multisets, but can be adapted to that, this is a custom set?

# ------------------

U           = [419, 3064, 3279, 5588, 9279, 10182, 10733, 11121, 11961, 12250, 12429, 14054, 14191, 15990, 16094, 16211]
S           = [11121, 15990, 9279, 3279, 419, 419, 16094, 16211, 3064]
T           = 75876
sum(S)      = 75876
|U|/B(U)    = 1.1428571428571428
B([T])      = 17
|U|         = 16
B(U)        = 14
time        = 0.13211798667907715

# ------------------

U           = [1166, 2063, 2328, 3396, 4546, 6817, 7417, 7497, 8398, 9816, 11221, 11434, 12068, 12429, 13584, 13743, 14325, 14921]
S           = [8398, 4546, 1166, 1166, 4546]
T           = 19822
sum(S)      = 19822
|U|/B(U)    = 1.2857142857142858
B([T])      = 15
|U|         = 18
B(U)        = 14
time        = 0.062428951263427734

**Comment by shimpe** [comment]
I just generated random problems by adding a random integer between 1-10 to the "zero" you generate in your ABS_final.py file.

**Comment by maxtuno** [comment]
you show me the code? to be clear, I do not see any entire 1 < 10 in the universe. you are happy with the answer? or still have more questions?
